---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-cinder-soc
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: openstack-cinder-chart-group-global
      component: cinder
    actions:
      - method: merge
        path: .sequenced
      - method: replace
        path: .chart_group
  storagePolicy: cleartext
data:
  sequenced: true
  chart_group:
    - cinder-soc
