---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: cinder-rabbitmq-soc
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: cinder-rabbitmq-global
      component: cinder
    actions:
      - method: delete
        path: .values.labels.prometheus_rabbitmq_exporter
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  wait:
    timeout: {{ openstack_helm_deploy_timeout }}
  test:
    enabled: {{ run_tests | default('true') }}
    timeout: {{ test_timeout | default(300) }}
  values:
    pod:
      replicas:
        server: 1
    monitoring:
      prometheus:
        enabled: false
    volume:
      size: {{ rabbitmq_volume_size }}
...
