---

- name: Creates certs directory
  file:
    path: "{{ suse_registry_certs_dir }}"
    state: directory

- name: Check if self-signed certifcate already exists
  stat:
    path: "{{ suse_registry_certs_dir }}/domain.crt"
  register: _domain_cert_check

- name: Create local self-signed certificate, if not already present
  command: >
     openssl req -x509 -newkey rsa:4096 -nodes
        -subj '/CN={{ ansible_hostname }}' \
        -days 365 \
        -keyout "{{ suse_registry_certs_dir }}/domain.key" \
        -out "{{ suse_registry_certs_dir }}/domain.crt"
  register: sscert_generate_result
  when:
    - not _domain_cert_check.stat.exists

- name: Get registry host (aka deployer) ip for entry in other host's /etc/hosts
  set_fact:
    registry_server_host_ip: "{{ ansible_default_ipv4.address | ipaddr('address') }}"

- name: Fetch self-signed cert to runner host
  fetch:
    src: "{{ suse_registry_certs_dir }}/domain.crt"
    dest: "/tmp/"
    flat: yes
