---
- name: Clone OpenStack-Helm related code repositories
  git:
    repo: "{{ item.value.src }}"
    dest: "{{suse_airship_deploy_repo_location }}/{{ item.key }}"
    update: yes
    force: yes
    version: "{{ item.value.version }}"
  with_dict: "{{ airship_repos }}"
  register: _gitclone
  until: _gitclone is succeeded
