---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-tempest-soc
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: tempest-global
      component: tempest
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  wait:
    timeout: 12000
{% if deploy_tempest is defined and deploy_tempest is sameas true %}
  values:
    pod:
      resources:
        enabled: {{ openstack_helm_pod_resources_enabled['tempest'] }}
    jobs:
      run_tests:
        backoffLimit: 0
        restartPolicy: Never
    conf:
      script: |
        tempest workspace register --path /var/lib/tempest/data --name default
        tempest run \
        --serial \
        --workspace default \
        --config-file /etc/tempest/tempest.conf \
        -w {{ tempest_workers }} \
        {{ tempest_test_args[tempest_test_type] }} \
{% if use_blacklist %}
        --blacklist-file /etc/tempest/test-blacklist \
{% endif %}
{% if tempest_subunit is defined and tempest_subunit is sameas true %}
        --subunit \
{% endif %}
        || true
{% if use_blacklist %}
      blacklist:
        {{ lookup('file', 'tempest_blacklist') | indent(8) }}
{% endif %}
      tempest:
        auth:
          tempest_roles: []
          admin_domain_name: "Default"
        identity:
          admin_domain_scope: true
          default_domain_id: "default"
        identity-feature-enabled:
          api_v2: false
          domain_specific_drivers: true
        image:
          http_image: "{{ cirros_test_image_url }}"
        compute:
          flavor_ref: "{{ tempest_test_flavor_id.stdout }}"
          image_ref: "{{ tempest_test_image_id.stdout }}"
          image_ref_alt: "{{ tempest_test_image_id.stdout }}"
          hypervisor_type: "{{ tempest_test_hypervisor_type | default('qemu') }}"
        network:
          default_network: "10.0.0.0/8"
          project_network_cidr: "{{ openstack_project_network_cidr }}"
          floating_network_name: "{{ openstack_external_network_name }}"
          public_network_id: "{{ tempest_public_network_details.stdout_lines[0] }}"
          shared_physical_network: "{{ tempest_public_network_details.stdout_lines[1] }}"
        validation:
          image_ssh_user: "cirros"
          image_ssh_password: "gocubsgo"
          network_for_ssh: "{{ openstack_external_network_name }}"
          floating_ip_range: "{{ openstack_external_subnet_cidr.stdout }}"
        service_available:
          cinder: "{{ tempest_enable_cinder_service }}"
          glance: "{{ tempest_enable_glance_service }}"
          nova: "{{ tempest_enable_nova_service }}"
          neutron: "{{ tempest_enable_neutron_service }}"
      cleanup:
        enabled: false
{% endif %}  
...
