apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- namespace.yaml
- upstream-install.yaml
- first-app--the-auto-deployer.yaml

patchesJson6902:
- target:
    kind: ConfigMap
    name: argocd-ssh-known-hosts-cm
    version: v1
  path: cleanup_known_hosts.yaml
