---

# TODO: may need better way to identify registry server.
registry_server_hostgroup: "soc-deployer"
registry_server_hostvars: "{{ hostvars[groups[registry_server_hostgroup][0]] }}"
registry_server_host_ip: "{{ registry_server_hostvars.ansible_default_ipv4.address | ipaddr('address') }}"

local_registry_name: "{{ registry_server_hostvars.ansible_hostname }}"
local_registry_port: 5000

suse_setup_registry_server: true
suse_registry_certs_dir: "{{ socok8s_deployer_workspace }}/certs"
suse_registry_create_certs: true

suse_registry_setup_packages:
  - docker
