---

local_registry_name: "{{ ansible_hostname }}"
local_registry_port: 5000

suse_setup_registry_server: true
suse_registry_certs_dir: "/certs"
suse_registry_create_certs: true

suse_registry_setup_packages:
  - docker
  - python-pyOpenSSL