---
- name: Show what will be built using LOCI
  debug:
    msg: "BUILD_PROJECTS: {{ ' '.join(loci_build_projects) }}"

- name: Build loci images in parallel (using OSH-images tooling)
  shell: "{{ loci_build_command | default('./openstack/loci/build.sh') }}"
  args:
    chdir: "{{ upstream_repos_clone_folder }}/openstack/openstack-helm-images"
  environment: "{{ build_environment | default({}) | combine(default_environment) }}"
  vars:
    default_environment:
      LOCI_SRC_DIR: "{{ upstream_repos_clone_folder }}/loci"
      REGISTRY_URI: "{{ build_registry }}openstackhelm/"
      BASE_IMAGE: leap15
      PUSH_TO_REGISTRY: YES
      BUILD_PROJECTS: "{{ ' '.join(loci_build_projects) }}"
      default_project_extra_build_args: "--build-arg REGISTRY_PROTOCOL=https --build-arg REGISTRY_INSECURE=True --build-arg PYTHON3=yes --force-rm --pull --no-cache"
  tags:
    - skip_ansible_lint
