---
- name: Include common vars
  include_vars: "{{ playbook_dir }}/../vars/common-vars.yml"

- name: Add utilities repository
  zypper_repository:
    name: SLE12-utilities
    repo: "{{ sle_utils_repository_url }}"
    state: present
    auto_import_keys: yes
    runrefresh: yes
  when:
    - "ansible_distribution_major_version == '12'"

- name: Install system packages for build images
  package:
    name: "{{ suse_build_images_packages }}"
    state: present
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
  tags:
    - install

- name: Build and push the non-LOCI components
  include_tasks: build-with-docker.yml
  loop: "{{ docker_images }}"
  loop_control:
    loop_var: image

# TODO(evrardjp): Ensure idempotency here
# In the meantime, skip_ansible_lint
- name: Build and push Openstack Services images via loci
  include_tasks: build-with-loci.yml
  when:
    - loci_build_projects | length > 0
