---
# Example ses_config.yml file
# This file should be place in ~/suse-osh-deploy on the deployer node
ceph_conf:
  cluster_network: 192.168.111.0/24
  fsid: f85b97cb-ce8c-375a-80cc-d7ce32ba797f
  mon_host: 192.168.111.124
  mon_initial_members: linux-qx79
  public_network: 192.168.111.0/24
cinder:
  key: AQCDH9tbV49jDxAAk+d2wdxsXRcSFzjf0DHWyw==
  rbd_store_pool: volumes
  rbd_store_user: cinder
cinder-backup:
  key: AQCSH9tbx9YzNBAA65C+mwyNdmqaRwokMcHAlQ==
  rbd_store_pool: cinder_backup
  rbd_store_user: cinder-backup
glance:
  key: AQCuH9tbCNUuLBAAImRsG9tgH2ArPPlu4pt0EQ==
  rbd_store_pool: images
  rbd_store_user: glance
libvirt:
  key: AQCDH9tbV49jDxAAk+d2wdxsXRcSFzjf0DHWyw==
  rbd_store_pool: vms
  rbd_store_user: cinder
nova:
  rbd_store_pool: nova
radosgw_urls: []
