# BEGIN ANSIBLE MANAGED BLOCK
ceph_admin_keyring_b64key: QVFCMzNlUmJBQUFBQUJBQVdqZGFHN2VxUXdhRlBzQ1NuanQvc3c9PQ==
ceph_user_keyring_b64key: QVFCMzNlUmJBQUFBQUJBQVdqZGFHN2VxUXdhRlBzQ1NuanQvc3c9PQ==
ceph_monitors_ips: ['192.168.86.205'] #list containing all ips of the host (which should be an AIO containing the mons).
# END ANSIBLE MANAGED BLOCK

caasp_cluster_master_nodes: [192.168.86.200]
caasp_cluster_worker_nodes: [192.168.86.201, 192.168.86.202, 192.168.86.203, 192.168.86.204]
caasp_cluster_worker_cp_nodes: [192.168.86.201, 192.168.86.202, 192.168.86.203, 192.168.86.204]


suse_osh_deploy_vip_with_cidr: 192.168.86.197

caasp_kubeconfig_via_cli: true
caasp_login_credentials:
  server_name: linux-eqli.lan
  server_port: 6443
  username: akant@suse.com
  password: password
