---
- name: Include common vars to know developer_mode value
  include_vars: "{{ playbook_dir }}/../vars/common-vars.yml"

- name: Copy the registry certificates
  include_tasks: copy-certificates.yml
  when:
    - "((developer_mode | default(False)) | bool) or ((socok8s_byo_certs | default(False)) | bool)"
