---
- name: Check subvolume directory already exists
  stat:
    path: /var/lib/nova
  register: _subvolume_check

- name: Check if subvolumes need to be created
  set_fact:
    suse_cp_node_create_subvolume: true
  when:
    - not _subvolume_check.stat.exists

- name: Add subvolume setup script
  template:
    src: caasp_cp_node_set_subvolumes.sh.j2
    dest: /tmp/caasp_cp_node_set_subvolumes.sh
    mode: "0755"
  when: suse_cp_node_create_subvolume


- name: Execute subvolume setup script
  shell: /tmp/caasp_cp_node_set_subvolumes.sh
  register: _cmd_out
  failed_when: _cmd_out.rc !=0
  when: suse_cp_node_create_subvolume

- name: Reboot node after successful subvolumes creation
  reboot: 
    msg: "Ansible triggered reboot after making subvolumes for Nova, Neutron and Libvirt"
    test_command: "kubectl get nodes"
  when: suse_cp_node_create_subvolume
