images:
  tags:
    barbican_api: 'docker.io/openstackhelm/barbican:queens'
    barbican_db_sync: 'docker.io/openstackhelm/barbican:queens'
    bootstrap: 'docker.io/openstackhelm/heat:queens'
    cinder_api: 'docker.io/openstackhelm/cinder:queens'
    cinder_backup: 'docker.io/openstackhelm/cinder:queens'
    cinder_db_sync: 'docker.io/openstackhelm/cinder:queens'
    cinder_scheduler: 'docker.io/openstackhelm/cinder:queens'
    cinder_volume: 'docker.io/openstackhelm/cinder:queens'
    cinder_volume_usage_audit: 'docker.io/openstackhelm/cinder:queens'
    congress_api: 'docker.io/openstackhelm/congress:queens'
    congress_datasource: 'docker.io/openstackhelm/congress:queens'
    congress_db_sync: 'docker.io/openstackhelm/congress:queens'
    congress_ds_create: 'docker.io/openstackhelm/congress:queens'
    congress_policy_engine: 'docker.io/openstackhelm/congress:queens'
    congress_scripted_test: 'docker.io/openstackhelm/congress:queens'
    db_drop: 'docker.io/openstackhelm/heat:queens'
    db_init: 'docker.io/openstackhelm/heat:queens'
    glance_api: 'docker.io/openstackhelm/glance:queens'
    glance_bootstrap: 'docker.io/openstackhelm/heat:queens'
    glance_db_sync: 'docker.io/openstackhelm/glance:queens'
    glance_registry: 'docker.io/openstackhelm/glance:queens'
    heat_api: 'docker.io/openstackhelm/heat:queens'
    heat_cfn: 'docker.io/openstackhelm/heat:queens'
    heat_cloudwatch: 'docker.io/openstackhelm/heat:queens'
    heat_db_sync: 'docker.io/openstackhelm/heat:queens'
    heat_engine: 'docker.io/openstackhelm/heat:queens'
    heat_engine_cleaner: 'docker.io/openstackhelm/heat:queens'
    horizon: 'docker.io/openstackhelm/horizon:queens-clients'
    horizon_db_sync: 'docker.io/openstackhelm/horizon:queens-clients'
    ironic_api: 'docker.io/openstackhelm/ironic:queens'
    ironic_bootstrap: 'docker.io/openstackhelm/ironic:queens'
    ironic_conductor: 'docker.io/openstackhelm/ironic:queens'
    ironic_db_sync: 'docker.io/openstackhelm/ironic:queens'
    ironic_pxe: 'docker.io/openstackhelm/ironic:queens'
    ironic_pxe_init: 'docker.io/openstackhelm/ironic:queens'
    keystone_api: 'docker.io/openstackhelm/keystone:queens'
    keystone_bootstrap: 'docker.io/openstackhelm/heat:queens'
    keystone_credential_rotate: 'docker.io/openstackhelm/keystone:queens'
    keystone_credential_setup: 'docker.io/openstackhelm/keystone:queens'
    keystone_db_sync: 'docker.io/openstackhelm/keystone:queens'
    keystone_domain_manage: 'docker.io/openstackhelm/keystone:queens'
    keystone_fernet_rotate: 'docker.io/openstackhelm/keystone:queens'
    keystone_fernet_setup: 'docker.io/openstackhelm/keystone:queens'
    ks_endpoints: 'docker.io/openstackhelm/heat:queens'
    ks_service: 'docker.io/openstackhelm/heat:queens'
    ks_user: 'docker.io/openstackhelm/heat:queens'
    magnum_api: 'docker.io/openstackhelm/magnum:queens'
    magnum_conductor: 'docker.io/openstackhelm/magnum:queens'
    magnum_db_sync: 'docker.io/openstackhelm/magnum:queens'
    neutron_db_sync: 'docker.io/openstackhelm/neutron:queens'
    neutron_dhcp: 'docker.io/openstackhelm/neutron:queens'
    neutron_l3: 'docker.io/openstackhelm/neutron:queens'
    neutron_linuxbridge_agent: 'docker.io/openstackhelm/neutron:queens'
    neutron_metadata: 'docker.io/openstackhelm/neutron:queens'
    neutron_openvswitch_agent: 'docker.io/openstackhelm/neutron:queens'
    neutron_server: 'docker.io/openstackhelm/neutron:queens'
    neutron_sriov_agent: 'docker.io/openstackhelm/neutron:queens-sriov-1804'
    neutron_sriov_agent_init: 'docker.io/openstackhelm/neutron:queens-sriov-1804'
    nova_api: 'docker.io/openstackhelm/nova:queens'
    nova_cell_setup: 'docker.io/openstackhelm/nova:queens'
    nova_compute: 'docker.io/openstackhelm/nova:queens'
    nova_compute_ironic: 'docker.io/kolla/ubuntu-source-nova-compute-ironic:queens'
    nova_compute_ssh: 'docker.io/openstackhelm/nova:queens'
    nova_conductor: 'docker.io/openstackhelm/nova:queens'
    nova_consoleauth: 'docker.io/openstackhelm/nova:queens'
    nova_db_sync: 'docker.io/openstackhelm/nova:queens'
    nova_novncproxy: 'docker.io/kolla/ubuntu-source-nova-novncproxy:queens'
    nova_novncproxy_assets: 'docker.io/kolla/ubuntu-source-nova-novncproxy:queens'
    nova_placement: 'docker.io/openstackhelm/nova:queens'
    nova_scheduler: 'docker.io/openstackhelm/nova:queens'
    nova_spiceproxy: 'docker.io/kolla/ubuntu-source-nova-spicehtml5proxy:queens'
    nova_spiceproxy_assets: 'docker.io/kolla/ubuntu-source-nova-spicehtml5proxy:queens'
    scripted_test: 'docker.io/openstackhelm/heat:queens'
    senlin_api: 'docker.io/openstackhelm/senlin:queens'
    senlin_db_sync: 'docker.io/openstackhelm/senlin:queens'
    senlin_engine: 'docker.io/openstackhelm/senlin:queens'
    tempest: 'docker.io/kolla/ubuntu-source-tempest:queens'
    test: 'docker.io/kolla/ubuntu-source-rally:queens'