---
- name: Install system packages for dev patcher
  package:
    name: "{{ suse_dev_patcher_packages }}"
    state: present
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
  tags:
    - install

- name: Clone OSH related repos
  import_tasks: clone-repos.yml
  tags:
    - run

- name: Apply upstream reviews in flight to OSH related repos
  include: patch-review-repos.yml
  with_items: "{{ osh_patchsets | default({}) }}"
  loop_control:
    loop_var: review_site
  tags:
    - run
