---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-memcached-soc
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: openstack-memcached-chart-group-global
      component: memcached
    actions:
      - method: replace
        path: .chart_group
  storagePolicy: cleartext
data:
  chart_group:
    - openstack-memcached-soc
...
