---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-horizon-soc
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: horizon-global
      component: horizon
    actions:
      - method: merge
        path: .
      - method: replace
        path: .values.pod
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/PodScaleProfile/v1
        name: pod-scale-profile
        path: .pods.osh.horizon.server.min
      dest:
        path: .values.pod.replicas.api
data:
  values:
    pod:
      replicas:
        server: 1
    conf:
      software:
        apache2:
          binary: apache2ctl
          start_parameters: -DFOREGROUND -k start
          site_dir: /etc/apache2/vhosts.d
          conf_dir: /etc/apache2/conf.d
          a2enmod:
            - rewrite
            - version
      horizon:
        security: |
          <Directory "/var/www">
          Options Indexes FollowSymLinks
          AllowOverride All
          <IfModule !mod_access_compat.c>
            Require all granted
          </IfModule>
          <IfModule mod_access_compat.c>
            Order allow,deny
            Allow from all
          </IfModule>
          </Directory>
