---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-horizon-ccp
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: horizon-global
      component: horizon
    actions:
      - method: merge
        path: .
      - method: replace
        path: .values.pod
  storagePolicy: cleartext
data:
  values:
    pod:
      replicas:
        server: 2
...
