---
# defaults file for suse-build-images

devenv_root: /opt

local_registry_name: local-registry
local_registry_port: 5000
openstack_svcs_build_image_version: stable/queens

suse_build_images_packages:
  - docker

osh_repos:
  openstack-helm-infra:
    src: https://git.openstack.org/openstack/openstack-helm-infra
    version: 5da44ee3095906d97808fe73b8d0f6617cd623c7  # commit ref 4th December 2018
  openstack-helm:
    src: https://git.openstack.org/openstack/openstack-helm
    version: 030868aee3e14122eac1d39a1bb2d154ef9c86c9  # frozen ref 4th December 2018
  openstack-helm-images:
    src: https://github.com/openstack/openstack-helm-images
    version: master
  loci:
    src: https://github.com/openstack/loci
    version: master

# Following configuration is defined per gerrit review site.
# Review site need to support unauthenticated access via its REST API.
# Right now, only review.openstack.org is used and REST APIs are used to
# identify latest patchset of a review.

# On a per-repo basis, you may specify a list of patchsets to apply by
# the review number in the URL. There is no need to specify the revision
# as the latest revision of the patchset will always be chosen.
osh_patchsets:
  - review_api_base_URL: "https://review.openstack.org/changes"
    repo_refs:
      - repo_ref: loci
        review_numbers:
          - 621051
      - repo_ref: openstack-helm-images
        review_numbers:
          - 621206
          - 621254
          - 621143
          - 621145

