---
dev_patcher_baseurl: "https://review.openstack.org/changes"

dev_patcher_packages:
  - git

#merged patches will be skipped
#unrelated patches will fail (because not cloned)
#conflicting patches will fail (because need resolving)
dev_patcher_patches:
  # loci: Support self-signed certificates docker registry
  - 637963
  # osh: Adapt Makefile for releasenotes
  - 639964
  # osh: Increase default logging
  - 639711
