---
dev_patcher_baseurl: "https://review.openstack.org/changes"

dev_patcher_packages:
  - git

#merged patches will be skipped
#unrelated patches will fail (because not cloned)
#conflicting patches will fail (because need resolving)
dev_patcher_patches:
  - 636229
  - 636240
  - 637327
  - 638301
