---
dev_patcher_baseurl: "https://review.openstack.org/changes"

dev_patcher_packages:
  - git

#merged patches will be skipped
#unrelated patches will fail (because not cloned)
#conflicting patches will fail (because need resolving)
dev_patcher_patches:
  # airship-treasuremap: Add the wait label to delete nova test pod when nova chart is upgraded
  - 645218
  # airship patches
  - 636229
  - 637327
  - 638301
  - 639495
  - 639861
  - 640115
  # osh: Remove remaining test pods before new test run
  - 634936
  # osh: Updating keystone-api to work with opensuse based image
  - 633847
  # osh: make ceilometer-api work on suse based images
  - 641802
  # osh: Allow more generic overrides for horizon
  - 645141
  # osh: Allow more generic overrides for nova placement-api
  - 642067
  # osh: Fix indent filter not properly adding a newline after toYaml
  - 642844
  # osh-images: Add rocky release script
  - 642415
  # osh: change the nova cache to dogpile.cache.memcached
  - 644821
  # osh: Add heat dashboard if available to horizon
  - 645543
