---
- name: Get openstack compute node id.
  shell: |
     set -o pipefail
     openstack compute service list | grep {{ compute_node_name }} | awk '{print $2}'
  environment:
    OS_CLOUD: openstack
  register: compute_id
  failed_when: false
  changed_when: false

- name: Validate compute node id.
  debug:
    msg: "Compute node {{ compute_node_name }} does not exists in openstack."
  when: compute_id is defined and compute_id.stdout | length | int == 0

- name: Get VM list from compute node.
  command: "openstack server list --host {{ compute_node_name }}"
  environment:
    OS_CLOUD: openstack
  register: vm_exist
  failed_when: false
  changed_when: false

- name: Validate VM(s) exists on compute node.
  fail:
    msg: "VM(s) exists on compute node {{ compute_node_name }}."
  when: vm_exist is defined and vm_exist.stdout | length | int != 0

- name: Check for control-plane label.
  shell: |
     set -o pipefail
     kubectl get node {{ compute_node_name }} --show-labels | grep openstack-control-plane=enabled
  register: node_label_result
  failed_when: false
  changed_when: false

- name: Remove openstack-compute-node label from compute node
  command: "kubectl label node {{ compute_node_name }} openstack-compute-node-"
  changed_when: false

- name: Remove openvswitch label from compute node.
  command: "kubectl label node {{ compute_node_name }} openvswitch-"
  when: node_label_result is defined and node_label_result.stdout | length | int == 0

- name: Wait for compute pods to terminate
  shell: |
     set -o pipefail
     kubectl get pods -n {{ openstack_namespace_name }} --field-selector spec.nodeName={{ compute_node_name }} | grep nova-compute
  register: nova_pod_name
  until: nova_pod_name.stdout | length | int == 0
  retries: 30
  delay: 10
  failed_when: false
  changed_when: false

- name: Delete openstack compute service.
  command: "openstack compute service delete {{ compute_id.stdout }}"
  environment:
    OS_CLOUD: openstack
  when: compute_id is defined and compute_id.stdout | length | int != 0
  failed_when: false
