---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-ingress-soc
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: ucp-ingress-global
    actions:
      - method: replace
        path: .values.pod
      - method: merge
        path: .
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/PodScaleProfile/v1
        name: pod-scale-profile
        path: .pods.ucp.ingress.ingress.min
      dest:
        path: .values.pod.replicas.ingress
    - src:
        schema: pegleg/PodScaleProfile/v1
        name: pod-scale-profile
        path: .pods.ucp.ingress.error_page.min
      dest:
        path: .values.pod.replicas.error_page
data:
  values:
    pod:
      replicas:
        ingress: 1
        error_page: 1
  source:
    type: local
    location: /armada/airship-components/openstack-helm-infra
    subpath: ingress
...
