---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-keystone-soc
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: ucp-keystone-global
      component: keystone
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/PodScaleProfile/v1
        name: pod-scale-profile
        path: .pods.ucp.keystone.api.min
      dest:
        path: .values.pod.replicas.api
data:
  wait:
    timeout: {{ ucp_deploy_timeout }}
  test:
    enabled: {{ run_rally_tests }}
  values:
    pod:
      replicas:
        api: 1
...
