---
- name: Include global vars
  include_vars: "{{ playbook_dir }}/../vars/common-vars.yml"

- name: Drop ceph conf and keys
  delegate_to: localhost
  copy:
    dest: "{{ socok8s_workspace }}/{{ item.item }}"
    content: "{{ item.content | b64decode }}"
    mode: 0644
  with_items:
    - "{{ hostvars[inventory_hostname].ceph_files.results }}"

- name: Fetch client cinder key for ses-config.yml
  delegate_to: localhost
  slurp:
    src: "{{ socok8s_workspace }}/ceph.client.cinder.keyring"
  register: client_cinder_file

- name: Fetch client cinder backup key for ses-config.yml
  delegate_to: localhost
  slurp:
    src: "{{ socok8s_workspace }}/ceph.client.cinder_backup.keyring"
  register: client_cinder_backup_file

- name: Fetch client glance key for ses-config.yml
  delegate_to: localhost
  slurp:
    src: "{{ socok8s_workspace }}/ceph.client.glance.keyring"
  register: client_glance_file

- name: Set client key facts for ses-config.yml
  set_fact:
    client_cinder_file_key: "{{ client_cinder_file['content'] | b64decode | regex_findall('\\bkey\\b\\s*=\\s*(.*)') | first }}"
    client_cinder_backup_file_key: "{{ client_cinder_backup_file['content'] | b64decode | regex_findall('\\bkey\\b\\s*=\\s*(.*)') | first }}"
    client_glance_file_key: "{{ client_glance_file['content'] | b64decode | regex_findall('\\bkey\\b\\s*=\\s*(.*)') | first }}"

- name: Generate ses-config.yml
  delegate_to: localhost
  template:
    src: "{{ playbook_dir }}/roles/common-ses/templates/ses-config.yml.j2"
    dest: "{{ socok8s_ses_pools_details }}"

- name: Find the admin keyring b64 value
  shell: |
    set -o pipefail
    ceph auth get-key client.admin | base64
  changed_when: false
  register: _clientadminkey

- name: Create user_variables
  delegate_to: localhost
  blockinfile:
    path: "{{ socok8s_extravars }}"
    create: yes
    block: |
      ceph_admin_keyring_b64key: {{ _clientadminkey.stdout_lines[0] }}
      ceph_user_keyring_b64key: {{ _clientadminkey.stdout_lines[0]  }}
      suse_deploy_ceph_mons: [{% for ip in ansible_all_ipv4_addresses %}'{{ ip }}:6789'{% if not loop.last %},{% endif %}{% endfor %}]
      #list containing all ips of the host (which should be an AIO containing the mons).
