---
# defaults file for suse-airship-deploy

# Location of the kubeconfig file, fetched from velum UI.
kubeconfig_file_path: "{{ socok8s_deploy_config_location }}/kubeconfig"

suse_airship_deploy_packages:
  - ca-certificates
  - make
  - jq
  - nmap
  - uuid-runtime
  - docker
  - curl
  - python2-setuptools
  - python2-pip
  - python-devel

suse_osh_client_packages:
  - kubectl

suse_airship_deploy_python_libs:
  - "cmd2<=0.8.7"
  - python-openstackclient
  - python-heatclient

# Keep this until helm is packaged as rpm
helm_download_url: "https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get"
