---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: libvirt-soc
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: libvirt-global
      component: libvirt
    actions:
      - method: replace
        path: .values
  storagePolicy: cleartext
data:
  wait:
    timeout: {{ openstack_helm_deploy_timeout }}
  values:
    pod:
      resources:
        eanbled: {{ openstack_helm_pod_resources_enabled['libvirt'] }}
    labels:
      agent:
        libvirt:
          node_selector_key: openstack-compute-node
          node_selector_value: enabled
    conf:
      ceph:
        enabled: true
        monitors: {{ ','.join(suse_airship_deploy_ceph_mons) }}
        admin_keyring: {{ ceph_admin_keyring_b64key | b64decode }}
        cinder:
          user: {{ ses_cluster_configuration.cinder.rbd_store_user }}
          keyring: {{ ses_cluster_configuration.cinder.key }}
          secret_uuid: {{ libvirt_ceph_cinder_secret_uuid }}
...
