---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: nova-soc
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: nova-global
      component: nova
    actions:
      - method: replace
        path: .values.labels.agent
      - method: delete
        path: .values.ceph_client
      - method: merge
        path: .values.conf
      - method: replace
        path: .values.pod
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/PodScaleProfile/v1
        name: pod-scale-profile
        path: .pods.osh.nova.api_metadata.min
      dest:
        path: .values.pod.replicas.api_metadata
    - src:
        schema: pegleg/PodScaleProfile/v1
        name: pod-scale-profile
        path: .pods.osh.nova.placement.min
      dest:
        path: .values.pod.replicas.placement
    - src:
        schema: pegleg/PodScaleProfile/v1
        name: pod-scale-profile
        path: .pods.osh.nova.osapi.min
      dest:
        path: .values.pod.replicas.osapi
    - src:
        schema: pegleg/PodScaleProfile/v1
        name: pod-scale-profile
        path: .pods.osh.nova.conductor.min
      dest:
        path: .values.pod.replicas.conductor
    - src:
        schema: pegleg/PodScaleProfile/v1
        name: pod-scale-profile
        path: .pods.osh.nova.consoleauth.min
      dest:
        path: .values.pod.replicas.consoleauth
    - src:
        schema: pegleg/PodScaleProfile/v1
        name: pod-scale-profile
        path: .pods.osh.nova.scheduler.min
      dest:
        path: .values.pod.replicas.scheduler
    - src:
        schema: pegleg/PodScaleProfile/v1
        name: pod-scale-profile
        path: .pods.osh.nova.novncproxy.min
      dest:
        path: .values.pod.replicas.novncproxy
data:
  wait:
    timeout: {{ openstack_helm_deploy_timeout }}
  test:
    enabled: {{ run_rally_tests }}
  values:
    labels:
      agent:
        compute:
          node_selector_key: openstack-compute-node
          node_selector_value: enabled
        compute_ironic:
          node_selector_key: openstack-compute-node
          node_selector_value: enabled
    conf:
      ceph:
        enabled: true
        monitors: {{ ','.join(suse_airship_deploy_ceph_mons) }}
        admin_keyring: {{ ceph_admin_keyring_b64key | b64decode }}
        cinder:
          user: {{ ses_cluster_configuration.cinder.rbd_store_user }}
          keyring: {{ ses_cluster_configuration.cinder.key }}
          secret_uuid: {{ libvirt_ceph_cinder_secret_uuid }}
      nova:
        libvirt:
          virt_type: qemu
    pod:
      replicas:
        api_metadata: 1 
        placement: 1
        osapi: 1
        conductor: 1
        consoleauth: 1
        scheduler: 1
        novncproxy: 1
...
