---
- hosts: osh-deployer
  gather_facts: yes
  any_errors_fatal: true
  pre_tasks:
    #http://jinja.pocoo.org/docs/2.10/templates/#default
    - name: Check if developer mode should be enabled
      set_fact:
        developer_mode: "{{ (lookup('env','OSH_DEVELOPER_MODE') | default('False', true) ) | bool }}"
      tags:
        - always
        - imagebuilder
        - upstream_patching
  roles:
    - role: install-docker
      tags:
        - docker
      when:
        - developer_mode
        - build_osh_images | default('False') | bool
    - role: suse-build-images
      tags:
        - imagebuilder
      when:
        - developer_mode
        - build_osh_images | default('False') | bool
