---
- hosts: soc-deployer[0]
  gather_facts: yes
  any_errors_fatal: true
  pre_tasks:
    - name: Set build_registry
      set_fact:
        build_registry: "{{ ansible_fqdn }}:5000/"

    #http://jinja.pocoo.org/docs/2.10/templates/#default
    - name: Check if developer mode should be enabled
      set_fact:
        developer_mode: "{{ (lookup('env','SOCOK8S_DEVELOPER_MODE') | default('False', true) ) | bool }}"
      tags:
        - always
        - imagebuilder
        - upstream_patching

    # The certificate generated before also needs to be known by the soc-deployer
    - name: If developer mode, install docker
      include_role:
        name: install-docker
        apply:
          tags:
            - docker
      when:
        - developer_mode

    - name: If developer mode, configure soc-deployer to include certs
      include_role:
        name: setup-caasp-workers
        tasks_from: copy-certificates
      when:
        - developer_mode

    - name: If developer mode, build suse images given in extravars or suse-build-images defaults.
      include_role:
        name: suse-build-images
        apply:
          tags:
            - imagebuilder
      when:
        - developer_mode
