---
- hosts: soc-deployer
  gather_facts: yes
  any_errors_fatal: true
  vars_files:
    - "{{ playbook_dir }}/../vars/common-vars.yml"
    - "{{ playbook_dir }}/../vars/deploy-on-openstack.yml"
  roles:
    - role: airship-setup-deployer
      vars:
        ext_vip: "{{ socok8s_ext_vip }}"
        zypper_extra_repos:
          socok8s: "{{ socok8s_repos_to_configure['socok8s_SLE15SP1'] }}"
      when: redeploy_osh_only is not defined or not redeploy_osh_only
      tags:
        - install

- name: Create SES pools for socok8s and import SES config to deployer
  hosts: ses_nodes[0]
  remote_user: root
  gather_facts: true
  roles:
    - common-ses

- hosts: soc-deployer:caasp-workers
  gather_facts: false
  any_errors_fatal: true
  roles:
    - role: registry-server-setup
      tags:
        - install
        - imagebuilder

- hosts: soc-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: dev-patcher
      when: redeploy_osh_only is not defined or not redeploy_osh_only
      become: yes
      tags:
        - upstream_patching

- hosts: soc-deployer
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - import_role:
        name: airship-configure-worker
        tasks_from: enroll-nodes
      when: redeploy_osh_only is not defined or not redeploy_osh_only
      tags:
        - install

- hosts: soc-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: suse-build-images
      when: build_airship_images | default('False') | bool
      tags:
        - install
        - imagebuilder

- hosts: soc-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: airship-configure-caasp
      when: redeploy_osh_only is not defined or not redeploy_osh_only
      tags:
        - install

- hosts: soc-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: airship-configure-ceph
      when: redeploy_osh_only is not defined or not redeploy_osh_only
      tags:
        - install

- hosts: soc-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: airship-deploy-ucp
      when: redeploy_osh_only is not defined or not redeploy_osh_only
      tags:
        - install
        - update_airship_ucp_site

- hosts: soc-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: airship-deploy-osh
      tags:
        - install
