---
- import_playbook: openstack-enroll_caasp_workers.yml
- import_playbook: openstack-prepare_caasp_workers_for_update.yml
- import_playbook: openstack-update-caasp-salt-grains.yml
- import_playbook: openstack-update_caasp.yml
