---
- hosts: soc-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: airship-setup-deployer
      when: redeploy_osh_only is not defined or not redeploy_osh_only
      tags:
        - install

- hosts: soc-deployer:caasp-workers
  gather_facts: false
  any_errors_fatal: true
  roles:
    - role: registry-server-setup
      tags:
        - install
        - imagebuilder

- hosts: soc-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: dev-patcher
      when: redeploy_osh_only is not defined or not redeploy_osh_only
      become: yes
      tags:
        - upstream_patching

- hosts: caasp-workers
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: airship-configure-worker
      when: redeploy_osh_only is not defined or not redeploy_osh_only
      tags:
        - install

- hosts: soc-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: suse-build-images
      when: build_airship_images | default('False') | bool
      tags:
        - install
        - imagebuilder

- hosts: soc-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: airship-configure-caasp
      when: redeploy_osh_only is not defined or not redeploy_osh_only
      tags:
        - install

- hosts: soc-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: airship-configure-ceph
      when: redeploy_osh_only is not defined or not redeploy_osh_only
      tags:
        - install

- hosts: soc-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: airship-deploy-ucp
      when: redeploy_osh_only is not defined or not redeploy_osh_only
      tags:
        - install
        - update_airship_ucp_site

- hosts: soc-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: airship-deploy-osh
      tags:
        - install
