---
- hosts: localhost
  gather_facts: no
  connection: local
  roles:
    - ansible-config_template
  post_tasks:
    - name: Load generic vars
      include_vars: "{{ playbook_dir }}/../vars/common-vars.yml"
    - name: Load openstack vars
      include_vars: "{{ playbook_dir }}/../vars/deploy-on-openstack.yml"

    - name: Define stackname to create
      set_fact:
        stackname: "{{ deploy_on_openstack_prefix }}-{{ lookup('env', 'BUILD_NUMBER') | default(65000 | random, true) }}"

    - name: Check if a stack already exists
      stat:
        path: "{{ deploy_on_openstack_caasp_stacknamefile }}"
      register: _stackfile

    - name: Handle creation if not exists
      when:
        - not ((caasp_stack_delete | default('false'))| bool)
      block:
        - name: Ensure no stack existed before continuing
          assert:
            that:
              - not _stackfile.stat.exists
            fail_msg: "A stack already exists, please remove all your stacks and your file {{ deploy_on_openstack_caasp_stacknamefile }} first"
            success_msg: "No stack exists, we can continue"

        - name: Create stack
          register: stackcreate
          os_stack:
            cloud: "{{ deploy_on_openstack_cloudname }}"
            state: "present"
            name: "{{ stackname }}"
            template: "{{ playbook_dir }}/../files/caasp-stack.yaml"
            parameters:
              image: "{{ deploy_on_openstack_caasp_image }}"
              external_net: "{{ deploy_on_openstack_external_network }}"
              internal_network: "{{ deploy_on_openstack_internal_network }}"
              internal_subnet: "{{ deploy_on_openstack_internal_subnet }}"
              security_group: "{{ deploy_on_openstack_caasp_securitygroup }}"
              keypair: "{{ deploy_on_openstack_keypairname }}"
              worker_count: "{{ deploy_on_openstack_caasp_workers }}"

        # Keep that as close to stack create, to prevent failures from not creating a lock
        - name: Save stackname for later (for deletion)
          copy:
            content: "{{ stackname }}"
            dest: "{{ deploy_on_openstack_caasp_stacknamefile }}"

        # TODO(evrardjp) Remove this when all the nodes have floating IPs in the template
        - name: Get all the node with no floating ips
          command: openstack server list --name {{ stackname | quote }}-worker -c ID -f json --noindent
          changed_when: false
          register: _workernodeswithnofloating
        # Do not reuse to prevent ssh issues or race conditions when running
        # multiple of those jobs at the same time.
        - name: Get a floating ip for the workers
          loop: "{{ _workernodeswithnofloating.stdout | from_json }}"
          os_floating_ip:
            cloud: "{{ deploy_on_openstack_cloudname }}"
            server: "{{ item.ID }}"
            reuse: no
            network: "{{ deploy_on_openstack_external_network }}"

        # TODO(evrardjp): Replace this with stack output
        - name: Get workers details
          command: openstack server list --name {{ stackname }}-worker -c ID -c Name -c Networks -f json --noindent
          register: _workermachines
          changed_when: false
        - name: Get admin details
          command: openstack server list --name {{ stackname }}-admin -c ID -c Name -c Networks -f json --noindent
          register: _adminmachines
          changed_when: false
        - name: Get master details
          command: openstack server list --name {{ stackname }}-master -c ID -c Name -c Networks -f json --noindent
          register: _mastermachines
          changed_when: false
        - name: Set the list of IDs per type of machine.
          set_fact:
            workers: "{{ _workermachines.stdout | from_json }}"
            admins: "{{ _adminmachines.stdout | from_json }}"
            masters: "{{ _mastermachines.stdout | from_json }}"

        # TODO(evrardjp): Replace with stack output
        - name: Create inventory hosts structures
          set_fact:
            workerinventory: "{ {% for node in workers %}\"{{ node.Name }}\": { \"ansible_host\":\"{{ node.Networks.split(',')[-1].replace(' ','') }}\" }{% if not loop.last %},{% endif %}{% endfor %} }"
            admininventory: "{ {% for node in admins %}\"{{ node.Name }}\": { \"ansible_host\":\"{{ node.Networks.split(',')[-1].replace(' ','') }}\" }{% if not loop.last %},{% endif %}{% endfor %} }"
            masterinventory: "{ {% for node in masters %}\"{{ node.Name }}\": { \"ansible_host\":\"{{ node.Networks.split(',')[-1].replace(' ','') }}\" }{% if not loop.last %},{% endif %}{% endfor %} }"

        # TODO(evrardjp): Replace with stack outputs
        - name: List IDs
          set_fact:
            workerids: "{{ workers | json_query('[*].ID') }}"
            adminids: "{{ admins | json_query('[*].ID') }}"
            masterids: "{{ masters | json_query('[*].ID') }}"

        - name: Run the caasp tooling
          shell: |
            # compatibility for caasp tooling requires the creation of ssh key
            if [ ! -d ../misc-files/ ]; then
                mkdir ../misc-files
            fi
            if [ ! -f ../misc-files/id_shared ]; then
                ssh-keygen -b 2048 -t rsa -f ../misc-files/id_shared -N ""
            fi
            ./tools/generate-environment {{ stackname | quote }}
            ./misc-tools/generate-ssh-config environment.json
            PYTHONUNBUFFERED=1 "./misc-tools/wait-for-velum" https://$(jq -r '.dashboardExternalHost' environment.json)
            cp environment.json {{ socok8s_caasp_environment_details }}
          args:
            chdir: "{{ playbook_dir }}/../files/"
            executable: /bin/bash

        # TODO(evrardjp): Parse the heat output when the heat template has changed
        - name: Port security disable on ports
          shell: |
            ## Get ports from instances IDs
            serverports=$(openstack port list --server {{ item | quote }} -c ID -f value)
            for port in $serverports; do
                ## Disable port security on those pesky instances
                openstack port set ${port} --no-security-group --disable-port-security
            done
          loop: "{{ workerids + adminids + masterids }}"
          args:
            chdir: "{{ playbook_dir }}/../files/"
            executable: /bin/bash

        - name: Create a VIP port for OSH
          os_port:
            cloud: "{{ deploy_on_openstack_cloudname }}"
            state: present
            name: "{{ stackname }}-vip"
            no_security_groups: True
            network: "{{ deploy_on_openstack_internal_network }}"
          register: _oshclustervip

        - name: Show VIP port creation results
          debug:
            var: _oshclustervip
            verbosity: 1

        # TODO(evrardjp): Use os_port to get that information
        # Environment variables don't work as part of command, therefore
        # shell has to be used, which causes lint to worry too much.
        - name: Display VIP ip
          shell: |
            portdetails=$(openstack port show {{ stackname }}-vip -c fixed_ips -f value | cut -f 1 -d ',')
            vip=$(eval ${portdetails} && echo $ip_address)
            echo $vip
          args:
            executable: /bin/bash
          register: _vipip
          changed_when: false
          tags:
            - skip_ansible_lint

        - name: Extend inventory in workspace with newly created caasp nodes
          config_template:
            src: "{{ socok8s_workspace }}/inventory/hosts.yml"
            dest: "{{ socok8s_workspace }}/inventory/hosts.yml"
            config_type: yaml
            config_overrides: "{{ caasp_overrides }}"
          vars:
            caasp_overrides:
              caasp-admin:
                hosts: "{{ admininventory }}"
              caasp-masters:
                hosts: "{{ masterinventory }}"
              caasp-workers:
                hosts: "{{ workerinventory }}"

        - name: Add vip with cidr in extravars
          lineinfile:
            path: "{{ socok8s_extravars }}"
            regexp: "^socok8s_deploy_vip_with_cidr.*"
            line: "socok8s_deploy_vip_with_cidr: {{ _vipip.stdout }}/24"

        - meta: refresh_inventory

        # Waiting for port is not enough, as the port might be up (systemd)
        # while ssh is not ready. Wait for connection is not good either
        # because the key is unknown.
        - name: Wait for a while for SSH to be properly booted up
          wait_for:
            timeout: 120

        - name: Get pubkey, and add it to known hosts
          shell: ssh-keyscan -H {{ hostvars[item]['ansible_host'] | quote }} >> ${HOME}/.ssh/known_hosts
          loop: "{{ groups['caasp-admin'] + groups['caasp-masters'] + groups['caasp-workers'] }}"
          args:
            executable: /bin/bash

    - name: Handle deletion
      when:
        - ((caasp_stack_delete | default('false'))| bool)
      block:
        - name: Delete stack
          os_stack:
            cloud: "{{ deploy_on_openstack_cloudname }}"
            name: "{{ lookup('file',deploy_on_openstack_caasp_stacknamefile) }}"
            state: absent

        - name: Remove host from known hosts
          known_hosts:
            state: absent
            name: "{{ hostvars[item]['ansible_host'] }}"
          loop: "{{ groups['caasp-admin'] + groups['caasp-masters'] + groups['caasp-workers'] }}"

        - name: Remove caasp files
          file:
            state: absent
            path: "{{ item }}"
          loop:
            - "{{ socok8s_caasp_environment_details }}"
            - "{{ deploy_on_openstack_caasp_stacknamefile }}"
