---
- hosts: soc-deployer
  gather_facts: no
  tasks:
    - name: Ensure all the common vars are loaded
      include_vars: "{{ playbook_dir }}/../vars/common-vars.yml"

    - name: Ensure all the openstack mechanism vars are loaded
      include_vars: "{{ playbook_dir }}/../vars/deploy-on-openstack.yml"

    - name: Collect repo files for removal
      find:
        paths: "/etc/zypp/repos.d/"
        patterns: "*.repo"
      register: repo_files

    - name: Clear existing repo config
      file:
        path: "{{ item['path'] }}"
        state: absent
      with_items: "{{ repo_files['files'] }}"

    - name: Disable delta rpms
      ini_file:
        path: /etc/zypp/zypp.conf
        section: main
        option: download.use_deltarpm
        value: "false"

    - name: Workaround stupid JeOS image bugs (bsc#1138727)
      shell: "test -L /etc/resolv.conf || netconfig update -f"
      args:
        executable: /bin/sh
        creates: /var/run/netconfig/resolv.conf

    - name: Configure host repositories
      zypper_repository:
        name: "{{ item }}"
        repo: "{{ socok8s_repos_to_configure[item] }}"
        autorefresh: True
        auto_import_keys: yes
        state: present
      loop: "{{ deploy_on_openstack_osh_repos_per_imagename[deploy_on_openstack_oshnode_image] }}"

    - name: Add known vendors
      blockinfile:
        path: /etc/zypp/vendors.d/opensuse
        block: |
          [main]
          vendors = suse,opensuse,obs://build.opensuse.org/Cloud:OpenStack,obs://build.opensuse.org/devel:languages:python
        create: yes

    - name: Zypper dist-upgrade
      zypper:
        name: '*'
        state: dist-upgrade
        update_cache: yes
        extra_args_precommand: "--gpg-auto-import-keys"

    #On some images this service is not defined and the systemctl command fails.
    #The failed_when false is temporary until I find out proper conditional on this task.
    - name: Disable firewall
      systemd:
        enabled: no
        name: "{{ item }}"
      failed_when: false
      with_items:
        - SuSEfirewall2_setup.service
        - SuSEfirewall2_init.service

    # TODO(evrardjp): Move this to native ansible module, and remove the
    # skip_ansible_lint
    - name: Prepare keys
      shell: |
        if [ ! -f ~/.ssh/id_rsa ]; then
          ssh-keygen -t rsa -f ~/.ssh/id_rsa -N ""
          cat .ssh/id_rsa.pub >> .ssh/authorized_keys
        fi
        ssh-keyscan -H  127.0.0.1 >> ~/.ssh/known_hosts
      args:
        executable: /bin/bash
        warn: False
      tags:
        - skip_ansible_lint

    - name: Reboot host
      reboot:
        reboot_timeout: 900
        connect_timeout: 90

    - name: Store facts
      setup:
