---
- hosts: localhost
  gather_facts: no
  connection: local
  vars:
    stackname_suffix: "caasp"
    ansible_python_interpreter: /usr/bin/python3
  post_tasks:
    - name: Load generic vars
      include_vars: "{{ playbook_dir }}/../vars/common-vars.yml"
    - name: Load openstack vars
      include_vars: "{{ playbook_dir }}/../vars/deploy-on-openstack.yml"

    - name: Define stackname to create
      set_fact:
        stackname: "{{ socok8s_envname }}-{{ stackname_suffix }}"

    - name: Delete OpenStack CaaSP
      block:
        - name: Delete stack
          os_stack:
            name: "{{ stackname }}"
            state: absent
            auth_type: "{{ os_auth_type }}"

        - name: Remove host from known hosts
          known_hosts:
            state: absent
            name: "{{ hostvars[item]['ansible_host'] | default('') }}"
          loop: "{{ groups['caasp-admin'] + groups['caasp-masters'] + groups['caasp-workers'] }}"

        - name: Remove caasp files
          file:
            state: absent
            path: "{{ item }}"
          loop:
            - "{{ socok8s_caasp_environment_details }}"
            - "{{ socok8s_workspace }}/inventory/caasp.yml"
