---
- hosts: localhost
  gather_facts: no
  connection: local
  pre_tasks:
    - name: Load generic vars
      include_vars: "{{ item }}"
      loop:
        - "{{ playbook_dir }}/../vars/common-vars.yml"
        - "{{ playbook_dir }}/../vars/deploy-on-openstack.yml"
  roles:
    - role: handle-nodes-on-openstack
      vars:
        servername: "{{ deploy_on_openstack_oshnode_server_name }}"
        flavor: "{{ deploy_on_openstack_oshnode_flavor }}"
        image: "{{ deploy_on_openstack_oshnode_image }}"
        network: "{{ deploy_on_openstack_internal_network }}"
        securitygroups:
          - "{{ deploy_on_openstack_oshnode_securitygroup }}"
        groupname_for_inventory: "soc-deployer"
        userdata: "{{ deploy_on_openstack_oshnode_userdata }}"
        delete: "{{ ((osh_node_delete | default('False')) | bool) }}"
