---
- hosts: localhost
  gather_facts: no
  connection: local
  post_tasks:
    - name: Load generic vars
      include_vars: "{{ playbook_dir }}/../vars/common-vars.yml"
    - name: Load openstack vars
      include_vars: "{{ playbook_dir }}/../vars/deploy-on-openstack.yml"

    - name: Create/Update openstack network
      block:
        - name: create network stack
          register: network_stack_create_output
          os_stack:
            state: "present"
            name: "{{ deploy_on_openstack_network_stackname }}"
            template: "{{ playbook_dir }}/../heat-templates/openstack-network.yml"
            parameters:
              prefix: "{{ socok8s_envname }}"
              network_external: "{{ deploy_on_openstack_external_network }}"
              network_internal_cidr: "{{ deploy_on_openstack_internal_subnet_cidr }}"

        - name: show network stack output
          debug:
            var: network_stack_create_output

    - name: Add vip with cidr in extravars
      delegate_to: localhost
      blockinfile:
        path: "{{ socok8s_extravars }}"
        create: yes
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR {{ item.output_key }}"
        block: |
          socok8s_{{ item.output_key }}: {{ item.output_value }}
      with_items: "{{ network_stack_create_output.stack.outputs }}"
      when: ( item.output_key == 'dcm_vip') or ( item.output_key == 'ext_vip' )
