---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-deckhand-soc
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: ucp-deckhand-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/PodScaleProfile/v1
        name: pod-scale-profile
        path: .pods.ucp.deckhand.deckhand.min
      dest:
        path: .values.pod.replicas.deckhand
data:
  wait:
    timeout: {{ ucp_deploy_timeout }}
  test:
    enabled: {{ run_tests }}
    timeout: {{ test_timeout }}
  values:
    pod:
      replicas:
        deckhand: 1
...
