# path to the terraform binary
terraform_binary_path: "{{ (lookup('env','TERRAFORM_BINARY_PATH') | default('/usr/bin/terraform', true) ) }}"

############################################################################
# skuba terraform openstack provider specific variables
############################################################################
# A image that is available in the OpenStack cloud. That image is used to deploy
# CaaSP 4 with the skuba ci terraforms
skuba_ci_terraform_openstack_image_name: "SLE-15-SP1-JeOS-GM"
# the username to log into the image
skuba_ci_terraform_openstack_image_username: "sles"
# the password to log into the image
skuba_ci_terraform_openstack_image_password: "linux"

############################################################################
# skuba terraform libvirt provider specific variables
############################################################################
# A image that is use for libvirt. That image is used to deploy
# CaaSP 4 with the skuba ci terraforms
skuba_ci_terraform_libvirt_image_uri: "http://download.suse.de/install/SLE-15-SP1-JeOS-GMC/SLES15-SP1-JeOS.x86_64-15.1-OpenStack-Cloud-GMC.qcow2"
# the username to log into the image
skuba_ci_terraform_libvirt_image_username: "sles"
# the password to log into the image
skuba_ci_terraform_libvirt_image_password: "linux"

############################################################################
# skuba terraform common variables
############################################################################
# Download mirror to use for internal IBS repositories
skuba_ci_terraform_ibs_mirror_uri: "http://download.suse.de/ibs"
# Download mirror to use for "official" products and updates (can e.g. point
# to a local rmt mirror)
skuba_ci_terraform_rmt_mirror_uri: "http://download.suse.de/ibs"
# number of master nodes
skuba_ci_terraform_master_count: 1
# number of worker nodes
skuba_ci_terraform_worker_count: 2
# the flavor name used for master nodes
skuba_ci_terraform_master_flavor: "m1.large"
# the flavor name used for worker nodes
skuba_ci_terraform_worker_flavor: "m1.medlarge"

# A public key file that is used by terraform when setting up nodes
# Login to the CaaSP 4 nodes is possible with this priv/pub key combination
skuba_ci_terraform_autorized_keys_files:
  - "{{ lookup('file', '/home/jenkins/.ssh/id_rsa.pub', errors='ignore') }}"
  - "{{ lookup('file', '{{ ansible_env.HOME }}/.ssh/id_rsa.pub', errors='ignore') }}"

# The directory where the skuba CI terraform data will be copied to
skuba_ci_terraform_workspace: "skuba-terraform-workspace"


# The directory where skuba creates the cluster in
skuba_cluster_basedir: "."
# The name that is used for the CaaSP 4 cluster
skuba_cluster_name: "caasp4-cluster"
